vim.keymap.set('n', '<leader>tn', function()
    require('config.go_tasks').test_nearest()
end, { desc = 'Go: run enclosing test function' })
vim.keymap.set('n', '<leader>tp', function()
    require('config.go_tasks').test_package()
end, { desc = 'Go: test current package' })
vim.keymap.set('n', '<leader>tr', function()
    require('config.go_tasks').rerun()
end, { desc = 'Go: rerun last task' })
vim.keymap.set('n', '<leader>tq', '<Cmd>copen<CR>', { desc = 'Open task failure locations' })
