#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

export TERM=alacritty
export EDITOR=nvim

source $HOME/.dotfiles/config/x11/xsetup

# Autostart
autostart="sxhkd"

for program in $autostart; do
    pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Autostart programs with arguments
picom --no-fading-openclose --backend xrender --vsync &

# Ensure that xrdb has finished running before moving on to start the WM/DE
[ -n "$xrdbpid" ] && wait "$xrdbpid"
