local env = dofile(os.getenv('NVIM_TEST_ROOT') .. '/tests/bootstrap.lua')
local root = env.temporary .. '/refactor-project'
vim.fn.mkdir(root .. '/.git', 'p')
local path = root .. '/source.lua'
vim.fn.writefile({ 'first', 'refactor this', 'last' }, path)
vim.cmd.edit(path)
local tasks = require('config.refactor')
tasks.setup()
assert(vim.fn.maparg('<C-q>', 'n', false, true).callback == tasks.add)
vim.api.nvim_win_set_cursor(0, { 2, 0 })
local item = tasks.add('extract helper')
tasks.add()
assert(#tasks.list(root) == 1, 'duplicate locations must not accumulate')
vim.api.nvim_buf_set_lines(0, 0, 0, false, { 'inserted' })
assert(tasks.list(root)[1].line == 3, 'task must follow edits')
vim.cmd.write()
tasks.quickfix()
local qfid = vim.fn.getqflist({ id = 0 }).id
assert(vim.fn.getqflist()[1].lnum == 3)
tasks.done()
assert(#tasks.list(root) == 0 and #tasks.list(root, true) == 1)
assert(#vim.fn.getqflist() == 0, 'completion must update exported quickfix')
vim.cmd.cclose()
vim.cmd.edit(path)
tasks.toggle(root, item.id)
vim.fn.setqflist({}, ' ', { title = 'Unrelated test errors', items = { { filename = path, lnum = 1, text = 'error' } } })
tasks.toggle(root, item.id)
assert(vim.fn.getqflist({ title = 0 }).title == 'Unrelated test errors')
assert(#vim.fn.getqflist() == 1, 'task changes must not replace test results')
assert(#vim.fn.getqflist({ id = qfid, items = 0 }).items == 0)
tasks.toggle(root, item.id)
-- Reload state as a new session, then relocate against a changed file.
vim.cmd('bwipeout!')
vim.fn.writefile({ 'external insertion', 'inserted', 'first', 'refactor this', 'last' }, path)
package.loaded['config.refactor'] = nil
tasks = require('config.refactor')
tasks.setup()
vim.cmd.edit(path)
assert(tasks.list(root)[1].line == 4, 'unique source context must relocate on reopening')
assert(tasks.list(root)[1].note == 'extract helper', 'note must survive reload')
local other = env.temporary .. '/refactor-other'
vim.fn.mkdir(other .. '/.git', 'p')
assert(#tasks.list(other, true) == 0, 'projects must be isolated')
-- Exercise the actual Telescope picker and its actions.
tasks.picker()
local function picker()
    local buf = vim.api.nvim_get_current_buf()
    local p = require('telescope.actions.state').get_current_picker(buf)
    assert(vim.wait(2000, function() return p.manager and p.manager:num_results() == 1 and p:get_selection() end, 10))
    return buf, p
end
local buf, p = picker()
vim.fn.maparg('<C-d>', 'i', false, true).callback()
assert(#tasks.list(root) == 0)
vim.fn.maparg('<C-a>', 'i', false, true).callback()
assert(vim.wait(2000, function() return p.manager:num_results() == 1 and p:get_selection() end, 10))
vim.fn.maparg('<C-d>', 'i', false, true).callback()
assert(#tasks.list(root) == 1)
require('telescope.actions').select_default(buf)
assert(vim.api.nvim_buf_get_name(0) == path and vim.fn.line('.') == 4)
tasks.picker()
buf, p = picker()
vim.fn.maparg('<C-x>', 'i', false, true).callback()
assert(#tasks.list(root, true) == 0)
require('telescope.actions').close(buf)
package.loaded['config.refactor'] = nil
tasks = require('config.refactor')
assert(#tasks.list(root, true) == 0, 'deleting the last task must persist')
print('PASS: refactor collection, extmarks, persistence, relocation, project isolation, quickfix ownership and Telescope actions')
vim.cmd('qa!')
